# MY FIRST PROGRAM

In [ ]:
myString <- ("HELLO WORLD")
print (myString)

[1] "HELLO WORLD"

# VARIABLES

In [ ]:
myString <- "HELLO WORLD"
num <- 10
floatingNum <- 9.5
isBool = TRUE

class (myString)
class (num)
class (floatingNum)
class (isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

[1] "HELLO WORLD"

# NUMERICAL OPERATORS

In [ ]:
x <- 5
y <- 6

sum <- x + y
difference <- x - y
product <- x * y
quotient <- x / y

print(sum)
print(difference)
print(product)
print(round(quotient, 2))

cat("\nSUM: ", sum, "\n")
cat("difference: ", difference, "\n")
cat("product: ", product, "\n")
cat("quotient: ", round(quotient, 2), "\n")

[1] 11
[1] -1
[1] 30
[1] 0.83

SUM:  11
difference:  -1
product:  30
quotient:  0.83

# USER INPUT

In [ ]:
name <- readline("ENTER NAME: ")
print(paste("NAME:", name))
cat("\n")
name <- readline("ENTER NAME: ")
cat("NAME:", name)

ENTER NAME: asdas
[1] "NAME: asdas"

ENTER NAME: asdasd
NAME: asdasd

# DECISION MAKING

In [ ]:
grade <- 75

if (grade < 75) {
  print("Failed")
}else{
  print("PASS")
}

[1] "PASS"

#LOOPING

In [ ]:
num <- 100

for(i in num:1)
print(i)

[1] 100
[1] 99
[1] 98
[1] 97
[1] 96
[1] 95
[1] 94
[1] 93
[1] 92
[1] 91
[1] 90
[1] 89
[1] 88
[1] 87
[1] 86
[1] 85
[1] 84
[1] 83
[1] 82
[1] 81
[1] 80
[1] 79
[1] 78
[1] 77
[1] 76
[1] 75
[1] 74
[1] 73
[1] 72
[1] 71
[1] 70
[1] 69
[1] 68
[1] 67
[1] 66
[1] 65
[1] 64
[1] 63
[1] 62
[1] 61
[1] 60
[1] 59
[1] 58
[1] 57
[1] 56
[1] 55
[1] 54
[1] 53
[1] 52
[1] 51
[1] 50
[1] 49
[1] 48
[1] 47
[1] 46
[1] 45
[1] 44
[1] 43
[1] 42
[1] 41
[1] 40
[1] 39
[1] 38
[1] 37
[1] 36
[1] 35
[1] 34
[1] 33
[1] 32
[1] 31
[1] 30
[1] 29
[1] 28
[1] 27
[1] 26
[1] 25
[1] 24
[1] 23
[1] 22
[1] 21
[1] 20
[1] 19
[1] 18
[1] 17
[1] 16
[1] 15
[1] 14
[1] 13
[1] 12
[1] 11
[1] 10
[1] 9
[1] 8
[1] 7
[1] 6
[1] 5
[1] 4
[1] 3
[1] 2
[1] 1

#FUNCTIONS

In [ ]:
addNumber <- function(a,b){
  return (a+b)
}
addNumber (1,2)

[1] 3

#Vectors

In [ ]:
grades <- c(76,62,85,86,90)

grades

cat("\nMEAN:",mean(grades))
cat("\nMAX",max(grades))
cat("\nMIN:",min(grades))
cat("\nSUM:",sum(grades))
cat("\nLength:",length(grades))

[1] 76 62 85 86 90

MEAN: 79.8
MAX 90
MIN: 62
SUM: 399
Length: 5

#MATRIX

In [ ]:
A <- matrix(c(1,2,3,4,5,6),nrow=3)
A

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

#LIST

In [ ]:
student <- list(
  name = "Val",
  age = 20,
  gwa = 2.22
)

student

$name
[1] "Val"

$Age
[1] 20

$GWA
[1] 2.22

#DATA FRAMES & CSV

In [ ]:
students <- data.frame(
  name=c("VAL","VEL","VIL"),
  age=c(20,21,22),
  gwa=c(1.1,2.2,3.3)
)

write.csv(students,"Students.csv")

students

  name age gwa
1 VAL  20  1.1
2 VEL  21  2.2
3 VIL  22  3.3

#READ CSV

In [ ]:
data <- read.csv("Students.csv")

head(data)
cat("\n")
summary(data)

  X name age gwa
1 1 VAL  20  1.1
2 2 VEL  21  2.2
3 3 VIL  22  3.3

       X              name        age            gwa
 Min.   :1.0   Length   :3   Min.   :20.0   Min.   :1.10
 1st Qu.:1.5   N.unique :3   1st Qu.:20.5   1st Qu.:1.65
 Median :2.0   N.blank  :0   Median :21.0   Median :2.20
 Mean   :2.0   Min.nchar:3   Mean   :21.0   Mean   :2.20
 3rd Qu.:2.5   Max.nchar:3   3rd Qu.:21.5   3rd Qu.:2.75
 Max.   :3.0                 Max.   :22.0   Max.   :3.30